# Generated by Django 5.0 on 2023-12-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Фантастика', 'Фантастика'), ('Биография', 'Биография'), ('Апокалипсис', 'Апокалипсис'), ('Детектикв', 'Детектив')], default='Фантастика', max_length=100),
        ),
    ]
