# Generated by Django 5.0 on 2023-12-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0005_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='nomer',
            field=models.IntegerField(default=0),
        ),
    ]
