# Generated by Django 5.0 on 2023-12-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0007_issuedbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='izdatelstvo',
            field=models.CharField(default='', max_length=200),
        ),
    ]
