# Generated by Django 5.0 on 2023-12-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0008_book_izdatelstvo'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
