# Generated by Django 5.0 on 2023-12-21 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0010_alter_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='vozrast',
            field=models.CharField(default='', max_length=10),
        ),
    ]
